// ALL SKIP STATEMENTS THAT AFFECT THIS SHADER!!!
// defined $LIGHTING_PREVIEW && defined $FASTPATH && $LIGHTING_PREVIEW && $FASTPATH

#pragma once
#include "shaderlib/cshader.h"
class neo_hudbacking_vs30_Static_Index
{
public:
	neo_hudbacking_vs30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_neo_hudbacking_vs30 1


class neo_hudbacking_vs30_Dynamic_Index
{
public:
	neo_hudbacking_vs30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_neo_hudbacking_vs30 1

